
export const FETCH_PRODUCT_LIST_PENDING='FETCH_PRODUCT_LIST_PENDING';
export const FETCH_PRODUCT_LIST_FULFILLED='FETCH_PRODUCT_LIST_FULFILLED';
export const FETCH_PRODUCT_LIST_REJECTED='FETCH_PRODUCT_LIST_REJECTED';


export const FETCH_PRODUCT_LIST_FILTERED_PENDING='FETCH_PRODUCT_LIST_FILTERED_PENDING';
export const FETCH_PRODUCT_LIST_FILTERED_FULFILLED='FETCH_PRODUCT_LIST_FILTERED_FULFILLED';
export const FETCH_PRODUCT_LIST_FILTERED_REJECTED='FETCH_PRODUCT_LIST_FILTERED_REJECTED';



